-- MySQL Script generated by MySQL Workbench
-- 05/22/17 22:05:44
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tlCity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tlCity` (
  `cityCode` VARCHAR(15) NOT NULL,
  `cityName` VARCHAR(105) NULL,
  PRIMARY KEY (`cityCode`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tblUser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tblUser` (
  `userID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(75) NULL,
  `password` VARCHAR(55) NULL,
  `firstname` NVARCHAR(40) NULL,
  `lastname` NVARCHAR(40) NULL,
  `dateOfBirth` DATE NULL,
  `registerDate` DATE NULL,
  `phoneNumber` INT NULL,
  `roleID` INT UNSIGNED NULL,
  `gender` TINYINT(1) NULL,
  `aboutMe` MEDIUMTEXT NULL,
  `status` INT NULL,
  `primayryAddress` NVARCHAR(255) NULL,
  `sencondAddress` NVARCHAR(255) NULL,
  `cityCode` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`userID`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `fk_tblUser_tlCity1_idx` (`cityCode` ASC),
  CONSTRAINT `fk_tblUser_tlCity1`
    FOREIGN KEY (`cityCode`)
    REFERENCES `mydb`.`tlCity` (`cityCode`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tblRole`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tblRole` (
  `roleID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `roleName` NVARCHAR(50) NULL,
  `userID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`roleID`),
  INDEX `fk_tblRole_tblUser1_idx` (`userID` ASC),
  CONSTRAINT `fk_tblRole_tblUser1`
    FOREIGN KEY (`userID`)
    REFERENCES `mydb`.`tblUser` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tblOrder`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tblOrder` (
  `orderID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `createdTime` DATETIME NULL,
  `status` INT NULL,
  `userID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`orderID`),
  INDEX `fk_tblOrder_tblUser1_idx` (`userID` ASC),
  CONSTRAINT `fk_tblOrder_tblUser1`
    FOREIGN KEY (`userID`)
    REFERENCES `mydb`.`tblUser` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tblOrderDetail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tblOrderDetail` (
  `orderDetailID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `productID` INT UNSIGNED NULL,
  `quantity` INT UNSIGNED NULL,
  `price` FLOAT NULL,
  `storeID` INT UNSIGNED NULL,
  `status` INT NULL,
  `orderID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`orderDetailID`),
  INDEX `fk_tblOrderDetail_tblOrder_idx` (`orderID` ASC),
  CONSTRAINT `fk_tblOrderDetail_tblOrder`
    FOREIGN KEY (`orderID`)
    REFERENCES `mydb`.`tblOrder` (`orderID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tblCategory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tblCategory` (
  `categoryID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `categoryName` NVARCHAR(95) NULL,
  PRIMARY KEY (`categoryID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tblTracking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tblTracking` (
  `count` INT NULL,
  `lastUpdate` DATETIME(100) NULL,
  `userID` INT UNSIGNED NOT NULL,
  `tblCategory_categoryID` INT UNSIGNED NOT NULL,
  INDEX `fk_tblTracking_tblUser1_idx` (`userID` ASC),
  INDEX `fk_tblTracking_tblCategory1_idx` (`tblCategory_categoryID` ASC),
  PRIMARY KEY (`userID`, `tblCategory_categoryID`),
  CONSTRAINT `fk_tblTracking_tblUser1`
    FOREIGN KEY (`userID`)
    REFERENCES `mydb`.`tblUser` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tblTracking_tblCategory1`
    FOREIGN KEY (`tblCategory_categoryID`)
    REFERENCES `mydb`.`tblCategory` (`categoryID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tblProject`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tblProject` (
  `projectID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `projectName` NVARCHAR(155) NULL,
  `address` NVARCHAR(255) NULL,
  `cost` FLOAT UNSIGNED NULL,
  `website` VARCHAR(145) NULL,
  `year` YEAR NULL,
  `keywords` NVARCHAR(145) NULL,
  `status` INT NULL,
  `userID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`projectID`),
  INDEX `fk_tblProject_tblUser1_idx` (`userID` ASC),
  CONSTRAINT `fk_tblProject_tblUser1`
    FOREIGN KEY (`userID`)
    REFERENCES `mydb`.`tblUser` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tblStyle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tblStyle` (
  `styleID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` NVARCHAR(45) NULL,
  PRIMARY KEY (`styleID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tblIdeaBookPhoto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tblIdeaBookPhoto` (
  `photoID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(355) NULL,
  `tilte` NVARCHAR(145) NULL,
  `description` NVARCHAR(555) NULL,
  `status` INT NULL,
  `tblProject_projectID` INT UNSIGNED NOT NULL,
  `tblCategory_categoryID` INT UNSIGNED NOT NULL,
  `tblStyle_styleID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`photoID`),
  INDEX `fk_tblIdeaBookPhoto_tblProject1_idx` (`tblProject_projectID` ASC),
  INDEX `fk_tblIdeaBookPhoto_tblCategory1_idx` (`tblCategory_categoryID` ASC),
  INDEX `fk_tblIdeaBookPhoto_tblStyle1_idx` (`tblStyle_styleID` ASC),
  CONSTRAINT `fk_tblIdeaBookPhoto_tblProject1`
    FOREIGN KEY (`tblProject_projectID`)
    REFERENCES `mydb`.`tblProject` (`projectID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tblIdeaBookPhoto_tblCategory1`
    FOREIGN KEY (`tblCategory_categoryID`)
    REFERENCES `mydb`.`tblCategory` (`categoryID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tblIdeaBookPhoto_tblStyle1`
    FOREIGN KEY (`tblStyle_styleID`)
    REFERENCES `mydb`.`tblStyle` (`styleID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tblStory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tblStory` (
  `storyID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` NVARCHAR(85) NULL,
  `content` NVARCHAR(545) NULL,
  `status` INT NULL,
  `userID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`storyID`),
  INDEX `fk_tblStory_tblUser1_idx` (`userID` ASC),
  CONSTRAINT `fk_tblStory_tblUser1`
    FOREIGN KEY (`userID`)
    REFERENCES `mydb`.`tblUser` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tblIdeaBook`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tblIdeaBook` (
  `ideaBookID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` NVARCHAR(85) NULL,
  `description` NVARCHAR(555) NULL,
  `isPublic` INT NULL,
  `status` VARCHAR(45) NULL,
  `userID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`ideaBookID`),
  INDEX `fk_tblIdeaBook_tblUser1_idx` (`userID` ASC),
  CONSTRAINT `fk_tblIdeaBook_tblUser1`
    FOREIGN KEY (`userID`)
    REFERENCES `mydb`.`tblUser` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tblIdeaBookPhoto_has_tblIdeaBook`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tblIdeaBookPhoto_has_tblIdeaBook` (
  `tblIdeaBookPhoto_photoID` INT UNSIGNED NOT NULL,
  `tblIdeaBook_ideaBookID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`tblIdeaBookPhoto_photoID`, `tblIdeaBook_ideaBookID`),
  INDEX `fk_tblIdeaBookPhoto_has_tblIdeaBook_tblIdeaBook1_idx` (`tblIdeaBook_ideaBookID` ASC),
  INDEX `fk_tblIdeaBookPhoto_has_tblIdeaBook_tblIdeaBookPhoto1_idx` (`tblIdeaBookPhoto_photoID` ASC),
  CONSTRAINT `fk_tblIdeaBookPhoto_has_tblIdeaBook_tblIdeaBookPhoto1`
    FOREIGN KEY (`tblIdeaBookPhoto_photoID`)
    REFERENCES `mydb`.`tblIdeaBookPhoto` (`photoID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tblIdeaBookPhoto_has_tblIdeaBook_tblIdeaBook1`
    FOREIGN KEY (`tblIdeaBook_ideaBookID`)
    REFERENCES `mydb`.`tblIdeaBook` (`ideaBookID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tblTypeOfWork`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tblTypeOfWork` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` NVARCHAR(85) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tblProfessional`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tblProfessional` (
  `nameProfessional` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `userID` INT UNSIGNED NOT NULL,
  `tblTypeOfWork_id` INT NOT NULL,
  PRIMARY KEY (`userID`),
  INDEX `fk_tblProfessional_tblUser2_idx` (`userID` ASC),
  INDEX `fk_tblProfessional_tblTypeOfWork1_idx` (`tblTypeOfWork_id` ASC),
  CONSTRAINT `fk_tblProfessional_tblUser2`
    FOREIGN KEY (`userID`)
    REFERENCES `mydb`.`tblUser` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tblProfessional_tblTypeOfWork1`
    FOREIGN KEY (`tblTypeOfWork_id`)
    REFERENCES `mydb`.`tblTypeOfWork` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tblSeller`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tblSeller` (
  `taxNumber` VARCHAR(45) NULL,
  `storeAddress` VARCHAR(245) NULL,
  `sellerName` VARCHAR(245) NULL,
  `startDate` DATE NULL,
  `dueDate` DATE NULL,
  `phone` INT NULL,
  `userID` INT UNSIGNED NOT NULL,
  INDEX `fk_tblSeller_tblProfessional1_idx` (`userID` ASC),
  PRIMARY KEY (`userID`),
  CONSTRAINT `fk_tblSeller_tblProfessional1`
    FOREIGN KEY (`userID`)
    REFERENCES `mydb`.`tblProfessional` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tblProduct`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tblProduct` (
  `productID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `productName` NVARCHAR(145) NULL,
  `barCode` VARCHAR(45) NULL,
  `descripsion` NVARCHAR(545) NULL,
  `price` FLOAT NULL,
  `quantity` INT NULL,
  `size` VARCHAR(45) NULL,
  `material` NVARCHAR(45) NULL,
  `warranty` NVARCHAR(45) NULL,
  `status` INT NULL,
  `tblSeller_userID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`productID`),
  INDEX `fk_tblProduct_tblSeller1_idx` (`tblSeller_userID` ASC),
  CONSTRAINT `fk_tblProduct_tblSeller1`
    FOREIGN KEY (`tblSeller_userID`)
    REFERENCES `mydb`.`tblSeller` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tblProductPhoto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tblProductPhoto` (
  `productPhotoID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(245) NULL,
  `title` NVARCHAR(115) NULL,
  `description` NVARCHAR(545) NULL,
  `status` INT NULL,
  `tblStyle_styleID` INT UNSIGNED NOT NULL,
  `tblCategory_categoryID` INT UNSIGNED NOT NULL,
  `tblProduct_productID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`productPhotoID`),
  INDEX `fk_tblProductPhoto_tblStyle1_idx` (`tblStyle_styleID` ASC),
  INDEX `fk_tblProductPhoto_tblCategory1_idx` (`tblCategory_categoryID` ASC),
  INDEX `fk_tblProductPhoto_tblProduct1_idx` (`tblProduct_productID` ASC),
  CONSTRAINT `fk_tblProductPhoto_tblStyle1`
    FOREIGN KEY (`tblStyle_styleID`)
    REFERENCES `mydb`.`tblStyle` (`styleID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tblProductPhoto_tblCategory1`
    FOREIGN KEY (`tblCategory_categoryID`)
    REFERENCES `mydb`.`tblCategory` (`categoryID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tblProductPhoto_tblProduct1`
    FOREIGN KEY (`tblProduct_productID`)
    REFERENCES `mydb`.`tblProduct` (`productID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tblAdmin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tblAdmin` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `password` VARCHAR(45) NULL,
  `email` VARCHAR(115) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tblProfessional`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tblProfessional` (
  `nameProfessional` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `userID` INT UNSIGNED NOT NULL,
  `tblTypeOfWork_id` INT NOT NULL,
  PRIMARY KEY (`userID`),
  INDEX `fk_tblProfessional_tblUser2_idx` (`userID` ASC),
  INDEX `fk_tblProfessional_tblTypeOfWork1_idx` (`tblTypeOfWork_id` ASC),
  CONSTRAINT `fk_tblProfessional_tblUser2`
    FOREIGN KEY (`userID`)
    REFERENCES `mydb`.`tblUser` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tblProfessional_tblTypeOfWork1`
    FOREIGN KEY (`tblTypeOfWork_id`)
    REFERENCES `mydb`.`tblTypeOfWork` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tblPromotion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tblPromotion` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` NVARCHAR(145) NULL,
  `description` NVARCHAR(545) NULL,
  `status` INT NULL,
  `startDate` DATE NULL,
  `endDate` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tblProduct_has_tblPromotion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tblProduct_has_tblPromotion` (
  `tblProduct_productID` INT UNSIGNED NOT NULL,
  `tblPromotion_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`tblProduct_productID`, `tblPromotion_id`),
  INDEX `fk_tblProduct_has_tblPromotion_tblPromotion1_idx` (`tblPromotion_id` ASC),
  INDEX `fk_tblProduct_has_tblPromotion_tblProduct1_idx` (`tblProduct_productID` ASC),
  CONSTRAINT `fk_tblProduct_has_tblPromotion_tblProduct1`
    FOREIGN KEY (`tblProduct_productID`)
    REFERENCES `mydb`.`tblProduct` (`productID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tblProduct_has_tblPromotion_tblPromotion1`
    FOREIGN KEY (`tblPromotion_id`)
    REFERENCES `mydb`.`tblPromotion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
